version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: many
      MYSQL_USER: rasit
      MYSQL_PASSWORD: spring
      MYSQL_ROOT_PASSWORD: spring
    networks:
      - comment
networks:
  comment:
    driver: bridge